# .github/workflows/playwright.yml
name: Playwright CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 1. Install Python deps
      - run: pip install -r requirements.txt

      # 2. Install browsers
      - run: python -m playwright install

      # 3. (Optional) Run a quick smoke test
      - run: |
          python - <<'PY'
          from playwright.sync_api import sync_playwright
          with sync_playwright() as p:
              b = p.chromium.launch()
              b.close()
          PY
